# TV Script Generation
In this project, you'll generate your own [Simpsons](https://en.wikipedia.org/wiki/The_Simpsons) TV scripts using RNNs.  You'll be using part of the [Simpsons dataset](https://www.kaggle.com/wcukierski/the-simpsons-by-the-data) of scripts from 27 seasons.  The Neural Network you'll build will generate a new TV script for a scene at [Moe's Tavern](https://simpsonswiki.com/wiki/Moe's_Tavern).
## Get the Data
The data is already provided for you.  You'll be using a subset of the original dataset.  It consists of only the scenes in Moe's Tavern.  This doesn't include other versions of the tavern, like "Moe's Cavern", "Flaming Moe's", "Uncle Moe's Family Feed-Bag", etc..

In [1]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import helper

data_dir = './data/simpsons/moes_tavern_lines.txt'
text = helper.load_data(data_dir)
# Ignore notice, since we don't use it for analysing the data
text = text[81:]

## Explore the Data
Play around with `view_sentence_range` to view different parts of the data.

In [2]:
view_sentence_range = (0, 10)

"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import numpy as np

print('Dataset Stats')
print('Roughly the number of unique words: {}'.format(len({word: None for word in text.split()})))
scenes = text.split('\n\n')
print('Number of scenes: {}'.format(len(scenes)))

sentence_count_scene = [scene.count('\n') for scene in scenes]
print('Average number of sentences in each scene: {}'.format(np.average(sentence_count_scene)))

sentences = [sentence for scene in scenes for sentence in scene.split('\n')]
print('Number of lines: {}'.format(len(sentences)))
word_count_sentence = [len(sentence.split()) for sentence in sentences]
print('Average number of words in each line: {}'.format(np.average(word_count_sentence)))

print()
print('The sentences {} to {}:'.format(*view_sentence_range))
print('\n'.join(text.split('\n')[view_sentence_range[0]:view_sentence_range[1]]))

Dataset Stats
Roughly the number of unique words: 11492
Number of scenes: 262
Average number of sentences in each scene: 15.251908396946565
Number of lines: 4258
Average number of words in each line: 11.50164396430249

The sentences 0 to 10:

Moe_Szyslak: (INTO PHONE) Moe's Tavern. Where the elite meet to drink.
Bart_Simpson: Eh, yeah, hello, is Mike there? Last name, Rotch.
Moe_Szyslak: (INTO PHONE) Hold on, I'll check. (TO BARFLIES) Mike Rotch. Mike Rotch. Hey, has anybody seen Mike Rotch, lately?
Moe_Szyslak: (INTO PHONE) Listen you little puke. One of these days I'm gonna catch you, and I'm gonna carve my name on your back with an ice pick.
Moe_Szyslak: What's the matter Homer? You're not your normal effervescent self.
Homer_Simpson: I got my problems, Moe. Give me another one.
Moe_Szyslak: Homer, hey, you should not drink to forget your problems.
Barney_Gumble: Yeah, you should only drink to enhance your social skills.



## Implement Preprocessing Functions
The first thing to do to any dataset is preprocessing.  Implement the following preprocessing functions below:
- Lookup Table
- Tokenize Punctuation

### Lookup Table
To create a word embedding, you first need to transform the words to ids.  In this function, create two dictionaries:
- Dictionary to go from the words to an id, we'll call `vocab_to_int`
- Dictionary to go from the id to word, we'll call `int_to_vocab`

Return these dictionaries in the following tuple `(vocab_to_int, int_to_vocab)`

In [3]:
import numpy as np
import problem_unittests as tests
from collections import Counter


def create_lookup_tables(text):
    """
    Create lookup tables for vocabulary
    :param text: The text of tv scripts split into words
    :return: A tuple of dicts (vocab_to_int, int_to_vocab)
    """
    counts = Counter(text)
    vocab = sorted(counts, key = counts.get, reverse=True)
    vocab_to_int = {word:i for i,word in enumerate(vocab)}
    int_to_vocab = {vocab_to_int[word]:word for i,word in enumerate(vocab)}
    # TODO: Implement Function
    return vocab_to_int, int_to_vocab


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_create_lookup_tables(create_lookup_tables)

Tests Passed


### Tokenize Punctuation
We'll be splitting the script into a word array using spaces as delimiters.  However, punctuations like periods and exclamation marks make it hard for the neural network to distinguish between the word "bye" and "bye!".

Implement the function `token_lookup` to return a dict that will be used to tokenize symbols like "!" into "||Exclamation_Mark||".  Create a dictionary for the following symbols where the symbol is the key and value is the token:
- Period ( . )
- Comma ( , )
- Quotation Mark ( " )
- Semicolon ( ; )
- Exclamation mark ( ! )
- Question mark ( ? )
- Left Parentheses ( ( )
- Right Parentheses ( ) )
- Dash ( -- )
- Return ( \n )

This dictionary will be used to token the symbols and add the delimiter (space) around it.  This separates the symbols as it's own word, making it easier for the neural network to predict on the next word. Make sure you don't use a token that could be confused as a word. Instead of using the token "dash", try using something like "||dash||".

In [4]:
def token_lookup():
    """
    Generate a dict to turn punctuation into a token.
    :return: Tokenize dictionary where the key is the punctuation and the value is the token
    """
    # TODO: Implement Function
    punctuation_dict ={
        '.':"||period||",
        ',':"||comma||",
        '"':"||quotation_mark||",
        ';':"||semicolon||",
        '!':"||exclamation_mark||",
        '?':"||question||",
        '(':"||left_parenthesis||",
        ')':"||right_parenthesis||",
        '--':"||dash||",
        '\n':"||return||"
    }
    return punctuation_dict

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_tokenize(token_lookup)

Tests Passed


## Preprocess all the data and save it
Running the code cell below will preprocess all the data and save it to file.

In [5]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
# Preprocess Training, Validation, and Testing Data
helper.preprocess_and_save_data(data_dir, token_lookup, create_lookup_tables)

# Check Point
This is your first checkpoint. If you ever decide to come back to this notebook or have to restart the notebook, you can start from here. The preprocessed data has been saved to disk.

In [6]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import helper
import numpy as np
import problem_unittests as tests

int_text, vocab_to_int, int_to_vocab, token_dict = helper.load_preprocess()

## Build the Neural Network
You'll build the components necessary to build a RNN by implementing the following functions below:
- get_inputs
- get_init_cell
- get_embed
- build_rnn
- build_nn
- get_batches

### Check the Version of TensorFlow and Access to GPU

In [7]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
from distutils.version import LooseVersion
import warnings
import tensorflow as tf

# Check TensorFlow Version
assert LooseVersion(tf.__version__) >= LooseVersion('1.3'), 'Please use TensorFlow version 1.3 or newer'
print('TensorFlow Version: {}'.format(tf.__version__))

# Check for a GPU
if not tf.test.gpu_device_name():
    warnings.warn('No GPU found. Please use a GPU to train your neural network.')
else:
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))

TensorFlow Version: 1.8.0
Default GPU Device: /device:GPU:0


### Input
Implement the `get_inputs()` function to create TF Placeholders for the Neural Network.  It should create the following placeholders:
- Input text placeholder named "input" using the [TF Placeholder](https://www.tensorflow.org/api_docs/python/tf/placeholder) `name` parameter.
- Targets placeholder
- Learning Rate placeholder

Return the placeholders in the following tuple `(Input, Targets, LearningRate)`

In [8]:
def get_inputs():
    """
    Create TF Placeholders for input, targets, and learning rate.
    :return: Tuple (input, targets, learning rate)
    """
    # TODO: Implement Function
    
    inputs = tf.placeholder(tf.int32,[None,None],name='input')
    targets = tf.placeholder(tf.int32,[None,None],name='targets')
    learning_rate = tf.placeholder(tf.float32,name='learning_rate')
    
    return inputs, targets, learning_rate


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_inputs(get_inputs)

Tests Passed


### Build RNN Cell and Initialize
Stack one or more [`BasicLSTMCells`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/BasicLSTMCell) in a [`MultiRNNCell`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/MultiRNNCell).
- The Rnn size should be set using `rnn_size`
- Initalize Cell State using the MultiRNNCell's [`zero_state()`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/MultiRNNCell#zero_state) function
    - Apply the name "initial_state" to the initial state using [`tf.identity()`](https://www.tensorflow.org/api_docs/python/tf/identity)

Return the cell and initial state in the following tuple `(Cell, InitialState)`

In [9]:
def get_init_cell(batch_size, rnn_size):
    """
    Create an RNN Cell and initialize it.
    :param batch_size: Size of batches
    :param rnn_size: Size of RNNs
    :return: Tuple (cell, initialize state)
    """
    # TODO: Implement Function
    
    lstm = tf.contrib.rnn.BasicLSTMCell(rnn_size)
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=0.5)
    cell = tf.contrib.rnn.MultiRNNCell([drop]*2)
    initial_state = cell.zero_state(batch_size,tf.float32)
    
    initialstate = tf.identity(initial_state,name='initial_state')
    
    return cell, initialstate


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_init_cell(get_init_cell)

Tests Passed


### Word Embedding
Apply embedding to `input_data` using TensorFlow.  Return the embedded sequence.

In [10]:
def get_embed(input_data, vocab_size, embed_dim):
    """
    Create embedding for <input_data>.
    :param input_data: TF placeholder for text input.
    :param vocab_size: Number of words in vocabulary.
    :param embed_dim: Number of embedding dimensions
    :return: Embedded input.
    """
    # TODO: Implement Function
    embedding = tf.Variable(tf.random_uniform((vocab_size,embed_dim),-1,1))
    embed = tf.nn.embedding_lookup(embedding, input_data)
    return embed


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_embed(get_embed)

Tests Passed


### Build RNN
You created a RNN Cell in the `get_init_cell()` function.  Time to use the cell to create a RNN.
- Build the RNN using the [`tf.nn.dynamic_rnn()`](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn)
 - Apply the name "final_state" to the final state using [`tf.identity()`](https://www.tensorflow.org/api_docs/python/tf/identity)

Return the outputs and final_state state in the following tuple `(Outputs, FinalState)` 

In [11]:
def build_rnn(cell, inputs):
    """
    Create a RNN using a RNN Cell
    :param cell: RNN Cell
    :param inputs: Input text data
    :return: Tuple (Outputs, Final State)
    """
    # TODO: Implement Function
    outputs, final_state = tf.nn.dynamic_rnn(cell,inputs, dtype=tf.float32)
    finalstate = tf.identity(final_state,name='final_state')
    return outputs, finalstate


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_build_rnn(build_rnn)

Tests Passed


### Build the Neural Network
Apply the functions you implemented above to:
- Apply embedding to `input_data` using your `get_embed(input_data, vocab_size, embed_dim)` function.
- Build RNN using `cell` and your `build_rnn(cell, inputs)` function.
- Apply a fully connected layer with a linear activation and `vocab_size` as the number of outputs.

Return the logits and final state in the following tuple (Logits, FinalState) 

In [12]:
def build_nn(cell, rnn_size, input_data, vocab_size, embed_dim):
    """
    Build part of the neural network
    :param cell: RNN cell
    :param rnn_size: Size of rnns
    :param input_data: Input data
    :param vocab_size: Vocabulary size
    :param embed_dim: Number of embedding dimensions
    :return: Tuple (Logits, FinalState)
    """
    # TODO: Implement Function
    embed = get_embed(input_data, vocab_size, embed_dim)
    outputs, finalstate = build_rnn(cell, embed)
    
    print(outputs.shape)
    
    logits = tf.contrib.layers.fully_connected(outputs, vocab_size, activation_fn=None)
    
    print(logits.shape)
    
    return logits, finalstate


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_build_nn(build_nn)

(128, 5, 256)
(128, 5, 27)
Tests Passed


### Batches
Implement `get_batches` to create batches of input and targets using `int_text`.  The batches should be a Numpy array with the shape `(number of batches, 2, batch size, sequence length)`. Each batch contains two elements:
- The first element is a single batch of **input** with the shape `[batch size, sequence length]`
- The second element is a single batch of **targets** with the shape `[batch size, sequence length]`

If you can't fill the last batch with enough data, drop the last batch.

For example, `get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 3, 2)` would return a Numpy array of the following:
```
[
  # First Batch
  [
    # Batch of Input
    [[ 1  2], [ 7  8], [13 14]]
    # Batch of targets
    [[ 2  3], [ 8  9], [14 15]]
  ]

  # Second Batch
  [
    # Batch of Input
    [[ 3  4], [ 9 10], [15 16]]
    # Batch of targets
    [[ 4  5], [10 11], [16 17]]
  ]

  # Third Batch
  [
    # Batch of Input
    [[ 5  6], [11 12], [17 18]]
    # Batch of targets
    [[ 6  7], [12 13], [18  1]]
  ]
]
```

Notice that the last target value in the last batch is the first input value of the first batch. In this case, `1`. This is a common technique used when creating sequence batches, although it is rather unintuitive.

In [13]:
def get_batches(int_text, batch_size, seq_length):
    """
    Return batches of input and target
    :param int_text: Text with the words replaced by their ids
    :param batch_size: The size of batch
    :param seq_length: The length of sequence
    :return: Batches as a Numpy array
    """
    # TODO: Implement Function
    
    #int_text = np.array(int_text)
    #chars_per_batch = batch_size * seq_length
    #n_batches = len(int_text)//chars_per_batch
    
#     int_text = int_text[:n_batches * chars_per_batch]
    
#     int_text = int_text.reshape((batch_size,-1))
    
#     batches_final = []
     
#     for n in range(0, int_text.shape[1], seq_length):
#         batches = []
#         x = int_text[:,n:n+seq_length]
#         y_temp = int_text[:, n+1:n+seq_length+1]
        
#         y = np.zeros(x.shape, dtype=x.dtype)
#         y[:,:y_temp.shape[1]] = y_temp
        
#         batches.append(x)
#         batches.append(y)
#         batches_final.append(batches)        
#     return np.array(batches_final)

    chars_per_batch = batch_size * seq_length
    n_batches = int(len(int_text) / chars_per_batch)
    x_data = np.array(int_text[:n_batches * chars_per_batch])
    y_data = np.array(int_text[1:n_batches * chars_per_batch + 1])
    y_data[-1] = x_data[0]
    
    x_batches = np.split(x_data.reshape(batch_size, -1), n_batches, 1)
    y_batches = np.split(y_data.reshape(batch_size, -1), n_batches, 1)
    
    print(x_batches[0].shape)
    
    return np.array(list(zip(x_batches,y_batches)))

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_batches(get_batches)

(128, 5)
Tests Passed


## Neural Network Training
### Hyperparameters
Tune the following parameters:

- Set `num_epochs` to the number of epochs.
- Set `batch_size` to the batch size.
- Set `rnn_size` to the size of the RNNs.
- Set `embed_dim` to the size of the embedding.
- Set `seq_length` to the length of sequence.
- Set `learning_rate` to the learning rate.
- Set `show_every_n_batches` to the number of batches the neural network should print progress.

In [32]:
# Number of Epochs
num_epochs = 1150
# Batch Size
batch_size = 256
# RNN Size
rnn_size = 256
# Embedding Dimension Size
embed_dim = 256
# Sequence Length
seq_length = 15
# Learning Rate
learning_rate = 0.001
# Show stats for every n number of batches
show_every_n_batches = 100

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
save_dir = './save'

### Build the Graph
Build the graph using the neural network you implemented.

In [33]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
from tensorflow.contrib import seq2seq

train_graph = tf.Graph()
with train_graph.as_default():
    vocab_size = len(int_to_vocab)
    print(vocab_size)
    print(len(int_text))
    input_text, targets, lr = get_inputs()
    input_data_shape = tf.shape(input_text)
    print("input_text : ",input_text)
    print("rnn_size : ",rnn_size)
    cell, initial_state = get_init_cell(input_data_shape[0], rnn_size)
    logits, final_state = build_nn(cell, rnn_size, input_text, vocab_size, embed_dim)

    # Probabilities for generating words
    probs = tf.nn.softmax(logits, name='probs')

    # Loss function
    cost = seq2seq.sequence_loss(
        logits,
        targets,
        tf.ones([input_data_shape[0], input_data_shape[1]]))

    # Optimizer
    optimizer = tf.train.AdamOptimizer(lr)

    # Gradient Clipping
    gradients = optimizer.compute_gradients(cost)
    capped_gradients = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gradients if grad is not None]
    train_op = optimizer.apply_gradients(capped_gradients)

6780
69101
input_text :  Tensor("input:0", shape=(?, ?), dtype=int32)
rnn_size :  256
(?, ?, 256)
(?, ?, 6780)


## Train
Train the neural network on the preprocessed data.  If you have a hard time getting a good loss, check the [forums](https://discussions.udacity.com/) to see if anyone is having the same problem.

In [34]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
batches = get_batches(int_text, batch_size, seq_length)

with tf.Session(graph=train_graph) as sess:
    sess.run(tf.global_variables_initializer())

    for epoch_i in range(num_epochs):
        state = sess.run(initial_state, {input_text: batches[0][0]})

        for batch_i, (x, y) in enumerate(batches):
            feed = {
                input_text: x,
                targets: y,
                initial_state: state,
                lr: learning_rate}
            train_loss, state, _ = sess.run([cost, final_state, train_op], feed)

            # Show every <show_every_n_batches> batches
            if (epoch_i * len(batches) + batch_i) % show_every_n_batches == 0:
                print('Epoch {:>3} Batch {:>4}/{}   train_loss = {:.3f}'.format(
                    epoch_i,
                    batch_i,
                    len(batches),
                    train_loss))

    # Save Model
    saver = tf.train.Saver()
    saver.save(sess, save_dir)
    print('Model Trained and Saved')

(256, 15)
Epoch   0 Batch    0/17   train_loss = 8.821
Epoch   5 Batch   15/17   train_loss = 6.052
Epoch  11 Batch   13/17   train_loss = 5.835
Epoch  17 Batch   11/17   train_loss = 5.556
Epoch  23 Batch    9/17   train_loss = 5.367
Epoch  29 Batch    7/17   train_loss = 5.069
Epoch  35 Batch    5/17   train_loss = 4.949
Epoch  41 Batch    3/17   train_loss = 4.851
Epoch  47 Batch    1/17   train_loss = 4.581
Epoch  52 Batch   16/17   train_loss = 4.533
Epoch  58 Batch   14/17   train_loss = 4.379
Epoch  64 Batch   12/17   train_loss = 4.310
Epoch  70 Batch   10/17   train_loss = 4.281
Epoch  76 Batch    8/17   train_loss = 4.139
Epoch  82 Batch    6/17   train_loss = 4.141
Epoch  88 Batch    4/17   train_loss = 4.037
Epoch  94 Batch    2/17   train_loss = 3.922
Epoch 100 Batch    0/17   train_loss = 3.957
Epoch 105 Batch   15/17   train_loss = 3.865
Epoch 111 Batch   13/17   train_loss = 3.795
Epoch 117 Batch   11/17   train_loss = 3.683
Epoch 123 Batch    9/17   train_loss = 3.692


Epoch 1070 Batch   10/17   train_loss = 1.017
Epoch 1076 Batch    8/17   train_loss = 0.987
Epoch 1082 Batch    6/17   train_loss = 1.027
Epoch 1088 Batch    4/17   train_loss = 0.997
Epoch 1094 Batch    2/17   train_loss = 1.008
Epoch 1100 Batch    0/17   train_loss = 0.943
Epoch 1105 Batch   15/17   train_loss = 0.967
Epoch 1111 Batch   13/17   train_loss = 0.967
Epoch 1117 Batch   11/17   train_loss = 0.958
Epoch 1123 Batch    9/17   train_loss = 0.985
Epoch 1129 Batch    7/17   train_loss = 0.949
Epoch 1135 Batch    5/17   train_loss = 0.960
Epoch 1141 Batch    3/17   train_loss = 0.977
Epoch 1147 Batch    1/17   train_loss = 0.923
Model Trained and Saved


## Save Parameters
Save `seq_length` and `save_dir` for generating a new TV script.

In [35]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
# Save parameters for checkpoint
helper.save_params((seq_length, save_dir))

# Checkpoint

In [36]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import tensorflow as tf
import numpy as np
import helper
import problem_unittests as tests

_, vocab_to_int, int_to_vocab, token_dict = helper.load_preprocess()
seq_length, load_dir = helper.load_params()

## Implement Generate Functions
### Get Tensors
Get tensors from `loaded_graph` using the function [`get_tensor_by_name()`](https://www.tensorflow.org/api_docs/python/tf/Graph#get_tensor_by_name).  Get the tensors using the following names:
- "input:0"
- "initial_state:0"
- "final_state:0"
- "probs:0"

Return the tensors in the following tuple `(InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)` 

In [37]:
def get_tensors(loaded_graph):
    """
    Get input, initial state, final state, and probabilities tensor from <loaded_graph>
    :param loaded_graph: TensorFlow graph loaded from file
    :return: Tuple (InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)
    """
    # TODO: Implement Function
    return  loaded_graph.get_tensor_by_name('input:0'), loaded_graph.get_tensor_by_name('initial_state:0'), loaded_graph.get_tensor_by_name('final_state:0'), loaded_graph.get_tensor_by_name('probs:0')


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_tensors(get_tensors)

Tests Passed


### Choose Word
Implement the `pick_word()` function to select the next word using `probabilities`.

In [38]:
def pick_word(probabilities, int_to_vocab):
    """
    Pick the next word in the generated text
    :param probabilities: Probabilites of the next word
    :param int_to_vocab: Dictionary of word ids as the keys and words as the values
    :return: String of the predicted word
    """
    import random
    print(probabilities)
    # TODO: Implement Function
    for i,word in enumerate(int_to_vocab):
        print(word)
        for prob in probabilities:
            if random.random() < prob:
                return int_to_vocab[word]


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_pick_word(pick_word)

[0.1  0.8  0.05 0.05]
0
Tests Passed


## Generate TV Script
This will generate the TV script for you.  Set `gen_length` to the length of TV script you want to generate.

In [40]:
gen_length = 200
# homer_simpson, moe_szyslak, or Barney_Gumble
prime_word = 'moe_szyslak'

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
loaded_graph = tf.Graph()
with tf.Session(graph=loaded_graph) as sess:
    # Load saved model
    loader = tf.train.import_meta_graph(load_dir + '.meta')
    loader.restore(sess, load_dir)

    # Get Tensors from loaded model
    input_text, initial_state, final_state, probs = get_tensors(loaded_graph)

    # Sentences generation setup
    gen_sentences = [prime_word + ':']
    prev_state = sess.run(initial_state, {input_text: np.array([[1]])})

    # Generate sentences
    for n in range(gen_length):
        # Dynamic Input
        dyn_input = [[vocab_to_int[word] for word in gen_sentences[-seq_length:]]]
        dyn_seq_length = len(dyn_input[0])

        # Get Prediction
        probabilities, prev_state = sess.run(
            [probs, final_state],
            {input_text: dyn_input, initial_state: prev_state})
        
        pred_word = pick_word(probabilities[0][dyn_seq_length-1], int_to_vocab)

        gen_sentences.append(pred_word)
    
    # Remove tokens
    tv_script = ' '.join(gen_sentences)
    for key, token in token_dict.items():
        ending = ' ' if key in ['\n', '(', '"'] else ''
        tv_script = tv_script.replace(' ' + token.lower(), key)
    tv_script = tv_script.replace('\n ', '\n')
    tv_script = tv_script.replace('( ', '(')
        
    print(tv_script)

INFO:tensorflow:Restoring parameters from ./save
[6.3462416e-03 1.2742947e-03 4.1585993e-03 ... 1.3112482e-10 1.4857197e-10
 1.4754067e-10]
0
1
[9.8342949e-04 4.8901435e-02 5.8101401e-10 ... 1.1509666e-16 1.1672915e-16
 1.1594274e-16]
0
[1.5902954e-04 3.3714637e-02 1.8731754e-08 ... 4.0975697e-15 5.0289769e-15
 4.2856898e-15]
0
[9.9868804e-01 1.8685155e-04 6.9881673e-07 ... 6.6420297e-21 5.8442003e-21
 5.5058894e-21]
0
[9.9954575e-01 4.2512074e-06 5.6063886e-08 ... 3.8612028e-22 4.2967004e-22
 3.1242146e-22]
0
[9.7003323e-01 2.1895439e-06 8.3520143e-07 ... 8.1613577e-18 7.3905469e-18
 9.9708607e-18]
0
[4.2786238e-01 3.4288203e-04 8.7247493e-08 ... 4.3925521e-17 4.5681238e-17
 4.2484357e-17]
0
1
[2.0934824e-08 4.7532027e-05 2.8962181e-20 ... 1.3653892e-16 1.6673351e-16
 2.0215896e-16]
0
[4.4167623e-02 1.5652712e-04 4.4416981e-09 ... 4.0455493e-19 3.7300782e-19
 4.0254752e-19]
0
[9.9992812e-01 5.0756608e-08 3.9788479e-06 ... 7.0144618e-26 8.6577398e-26
 4.3000740e-26]
0
[8.4958449e-03 9.

 2.0524940e-16]
0
[6.2466337e-05 2.4459814e-04 3.0416071e-12 ... 2.3722893e-18 1.5143520e-18
 2.1988686e-18]
0
[9.9598467e-01 3.2659736e-05 9.2837418e-08 ... 1.5837190e-21 1.2579442e-21
 1.8765992e-21]
0
[8.6234808e-01 5.6917979e-05 1.4369175e-09 ... 4.4657459e-20 6.9490267e-20
 5.7257158e-20]
0
[4.4005759e-07 2.5564266e-04 2.6125439e-11 ... 3.2221754e-18 3.7492846e-18
 4.1034515e-18]
0
[9.9889392e-01 3.5975490e-06 1.1093173e-06 ... 9.0636212e-23 5.9171011e-23
 6.6854409e-23]
0
[7.6590800e-01 9.3026574e-07 1.5136216e-07 ... 2.2772809e-16 2.8976370e-16
 2.2657043e-16]
0
[2.2110456e-05 9.9629670e-01 2.8980773e-13 ... 9.2331544e-19 1.3662020e-18
 1.0824876e-18]
0
[9.5063514e-01 3.3835764e-05 3.3626684e-06 ... 1.4710711e-21 9.3503044e-22
 7.8412244e-22]
0
[4.3358389e-01 9.1182597e-02 4.3904652e-08 ... 2.0704283e-18 2.2111932e-18
 1.7439010e-18]
0
[7.1101017e-02 1.3612375e-01 1.8596609e-11 ... 6.7580325e-24 7.2471855e-24
 1.0957952e-23]
0
[1.08088090e-04 1.88234751e-03 4.88404517e-14 ... 8.

[1.3524960e-01 5.6510878e-04 6.6438822e-08 ... 9.7131593e-20 1.0679953e-19
 9.4619497e-20]
0
[9.73246574e-01 1.16639305e-04 5.08454286e-06 ... 1.48367847e-15
 1.65315643e-15 1.67251558e-15]
0
[9.5013964e-01 3.1551786e-02 1.7375952e-09 ... 5.8327815e-22 5.2179511e-22
 4.7415837e-22]
0
[8.6697417e-01 3.7603686e-04 2.2087598e-03 ... 3.3970543e-21 4.1670827e-21
 3.1077897e-21]
0
[8.9235413e-01 7.7187389e-02 7.5356076e-11 ... 3.4814394e-18 2.6414261e-18
 3.6833240e-18]
0
[9.6367139e-01 2.0421398e-04 2.3070781e-02 ... 4.4755827e-21 5.9720861e-21
 3.8466427e-21]
0
[9.7924393e-01 6.9036003e-05 5.7447158e-07 ... 2.1208211e-22 2.3953705e-22
 2.4276408e-22]
0
[9.5762062e-01 3.9621102e-11 4.1517636e-04 ... 5.0850741e-22 5.0660218e-22
 6.6022993e-22]
0
[3.4233071e-03 1.0999791e-02 4.6912385e-10 ... 7.1460210e-16 8.8376331e-16
 9.2603465e-16]
0
[9.984352e-01 5.001713e-05 7.377320e-05 ... 5.087936e-20 6.028077e-20
 4.888580e-20]
0
[8.4423009e-06 1.8604079e-01 5.5769782e-13 ... 3.6362396e-22 6.4768600

# The TV Script is Nonsensical
It's ok if the TV script doesn't make any sense.  We trained on less than a megabyte of text.  In order to get good results, you'll have to use a smaller vocabulary or get more data.  Luckily there's more data!  As we mentioned in the beggining of this project, this is a subset of [another dataset](https://www.kaggle.com/wcukierski/the-simpsons-by-the-data).  We didn't have you train on all the data, because that would take too long.  However, you are free to train your neural network on all the data.  After you complete the project, of course.
# Submitting This Project
When submitting this project, make sure to run all the cells before saving the notebook. Save the notebook file as "dlnd_tv_script_generation.ipynb" and save it as a HTML file under "File" -> "Download as". Include the "helper.py" and "problem_unittests.py" files in your submission.